apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: tpg
  labels:
    app: discovery-service
    group: general
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
        group: general
        version: v1
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:latest
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 60